# =============================================================================
# PinPal Status Page - Powered by Upptime
# https://github.com/felipekinder/pinpal-status
# =============================================================================

owner: felipekinder
repo: pinpal-status

sites:
  # ── Web App (Frontend - Firebase Hosting) ──
  - name: PinPal Web App
    url: https://thepinpal.com
    icon: https://thepinpal.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 301
      - 302

  # ── API Backend (Cloud Run) ──
  - name: PinPal API
    url: https://api.thepinpal.com/health
    expectedStatusCodes:
      - 200

  # ── API - Auth Endpoint ──
  - name: Authentication Service
    url: https://api.thepinpal.com/api/auth/status
    expectedStatusCodes:
      - 200
      - 401

  # ── WebSocket (TCP check) ──
  - name: WebSocket Service
    url: api.thepinpal.com
    port: 443
    check: "tcp-ping"

status-website:
  # Para usar domínio customizado (status.thepinpal.com), descomente:
  # cname: status.thepinpal.com
  baseUrl: /pinpal-status
  logoUrl: https://thepinpal.com/favicon.ico
  name: PinPal Status
  theme: light
  introTitle: "**PinPal** Status Page"
  introMessage: This page shows real-time availability and uptime data for PinPal services. Powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: PinPal
      href: https://thepinpal.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# ── Notifications (optional - configure later) ──
# notifications:
#   - type: slack
#     url: $SLACK_WEBHOOK_URL
#   - type: email
#     to: team@thepinpal.com

# ── Uptime schedule ──
workflowSchedule:
  graphs: "0 0 * * *"       # Daily graph updates
  responseTime: "0 23 * * *" # Daily response time
  staticSite: "0 1 * * *"   # Daily static site rebuild
  summary: "0 0 * * *"      # Daily summary
  updateTemplate: "0 0 * * *" # Daily template update
  uptime: "*/5 * * * *"     # Check every 5 minutes

# ── Issue creation settings ──
assignees:
  - felipekinder

i18n:
  activeIncidents: Active Incidents
  allOperational: All systems operational
  incidentReport: Incident Report
  activeMaintenances: Active Maintenances
  scheduledMaintenances: Scheduled Maintenances
  overallUptime: Overall Uptime
  liveStatus: Live Status
